# Generated by Django 5.0.6 on 2026-10-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_tools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmenttoolsdocument",
            name="doc_title",
            field=models.CharField(
                default="Assessment Tools for CO Attainment", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="assessmenttoolsdocument",
            name="sub_heading",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="assessmenttoolsdocument",
            name="watermark_text",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
