# Generated by Django 5.0.6 on 2026-09-12 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_year', models.PositiveSmallIntegerField()),
                ('semester_type', models.CharField(choices=[('ODD', 'Odd'), ('EVEN', 'Even')], max_length=6)),
            ],
            options={
                'ordering': ['-calendar_year', 'semester_type'],
            },
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('campus', models.CharField(choices=[('SECTOR_62', 'Sector-62'), ('SECTOR_128', 'Sector-128'), ('UNKNOWN', 'Not set')], default='UNKNOWN', max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('employee_id', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='NbaSubjectCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=120)),
                ('course_code', models.CharField(max_length=40)),
                ('course_name', models.CharField(max_length=255)),
                ('year_of_study', models.PositiveSmallIntegerField()),
                ('semester_number', models.PositiveSmallIntegerField()),
                ('nba_code', models.CharField(max_length=20)),
                ('credits', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['session', 'program_name', 'nba_code', 'course_code'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='semester_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='year_of_study',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='academic_year',
            field=models.CharField(help_text='Session label, e.g. 2026 Odd', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='academicsession',
            constraint=models.UniqueConstraint(fields=('calendar_year', 'semester_type'), name='unique_academic_session'),
        ),
        migrations.AddField(
            model_name='course',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings', to='courses.academicsession'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='course_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_offerings', to='courses.facultyprofile'),
        ),
        migrations.AddField(
            model_name='course',
            name='teaching_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_offerings', to='courses.facultyprofile'),
        ),
        migrations.AddField(
            model_name='nbasubjectcatalog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='courses.academicsession'),
        ),
        migrations.AddField(
            model_name='course',
            name='catalog_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings', to='courses.nbasubjectcatalog'),
        ),
        migrations.AddConstraint(
            model_name='facultyprofile',
            constraint=models.UniqueConstraint(fields=('full_name', 'campus'), name='unique_faculty_name_campus'),
        ),
        migrations.AddConstraint(
            model_name='nbasubjectcatalog',
            constraint=models.UniqueConstraint(fields=('session', 'nba_code', 'course_code'), name='unique_nba_course_per_session'),
        ),
    ]
